# This script is automatically triggered when a tag corresponding to a new version is pushed
# That will cause the build to be published to npm
name: publish

on:
  push:
    tags: [v*]

permissions:
  contents: read  # required for accessing repository contents
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.7.0'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci --no-audit
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READWRITE_TOKEN }}
        run: npm publish
