# Run this script manually to bump the version number and trigger a publish
name: release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Increment the version by the specified level. Level can be one of: major, minor, patch'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.7.0'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm version ${{ inputs.level }}
      - name: git config
        run: |
          git config user.name 'Warwick ✠'
          git config user.email warwick@globalworldwide.com
      - run: git push origin --follow-tags
